name: "c4ddev"
source-directory: "lib"
version: "1.7.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "C4DDev is a set of command-line tools and Cinema 4D plugins to make development plugins easier."
url: "https://github.com/NiklasRosenstein/c4ddev"
requirements:
  - python ^2.7 | ^3.4
  - bs4 ^4.6.0
  - click >=6.7
  - requests ^2.19.1
  - six ^1.11.0
