[statigen]
template = "default/docs"
contentDirectory = "content"

[site]
title = "C4DDev"
github = "https://github.com/NiklasRosenstein/c4ddev"

[author]
name = "Niklas Rosenstein"
email = "rosensteinniklas@gmail.com"
github = "NiklasRosenstein"
